"""add_google_auth

Revision ID: e057c5581fd8
Revises: a95bf052ec14
Create Date: 2024-05-23 12:32:04.930018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e057c5581fd8'
down_revision: Union[str, None] = 'a95bf052ec14'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_google_user', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'is_google_user')
    # ### end Alembic commands ###
